import type { Opportunity } from "./types";

const now = new Date();
const daysFromNow = (days: number) => {
  const date = new Date(now);
  date.setDate(date.getDate() + days);
  return date.toISOString();
};

export const demoOpportunities: Opportunity[] = [
  {
    id: "opportunity-ai-hackathon",
    title: "India AI Builders Hackathon",
    description:
      "Build practical AI applications for education, climate, finance, or public good. Teams can submit a working prototype and pitch to a panel of builders.",
    summary: "Build an AI prototype with mentors, peer teams, and a final demo day.",
    category: "Hackathon",
    organizer: "Open Innovation Collective",
    officialUrl: "https://example.com/ai-builders",
    sourceUrl: "https://example.com/ai-builders",
    sourceType: "official",
    format: "hybrid",
    location: "Bengaluru + online",
    eventStartDate: daysFromNow(18),
    eventEndDate: daysFromNow(20),
    registrationDeadline: daysFromNow(7),
    eligibility: "Students, recent graduates, and early-career builders in India.",
    fees: "Free",
    benefit: "Mentorship, certificates, prizes, and demo-day exposure.",
    skills: ["AI", "Python", "Product", "Design"],
    tags: ["beginner-friendly", "team-based", "india"],
    verificationStatus: "officially_verified",
    aiConfidence: 0.98,
    status: "published",
    lastVerifiedAt: now.toISOString(),
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: "opportunity-design-sprint",
    title: "Student Product Design Sprint",
    description:
      "A weekend sprint for students to solve a real product problem, receive feedback from designers, and publish a case study.",
    summary: "Turn a product problem into a polished case study in one weekend.",
    category: "Workshop",
    organizer: "Product School Network",
    officialUrl: "https://example.com/design-sprint",
    sourceUrl: "https://example.com/design-sprint",
    sourceType: "community",
    format: "online",
    location: "Online",
    eventStartDate: daysFromNow(12),
    eventEndDate: daysFromNow(13),
    registrationDeadline: daysFromNow(5),
    eligibility: "Open to students interested in UX, product, research, or visual design.",
    fees: "Free",
    benefit: "Mentor feedback, portfolio artifact, and participation certificate.",
    skills: ["UX", "Research", "Product Design"],
    tags: ["portfolio", "online", "beginner-friendly"],
    verificationStatus: "community_submitted",
    aiConfidence: 0.86,
    status: "published",
    lastVerifiedAt: now.toISOString(),
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: "opportunity-scholarship",
    title: "Future Leaders Scholarship",
    description:
      "Scholarship support for students building community projects or demonstrating leadership through volunteering, research, or entrepreneurship.",
    summary: "Funding support for student leaders building measurable community impact.",
    category: "Scholarship",
    organizer: "Future Leaders Foundation",
    officialUrl: "https://example.com/future-leaders",
    sourceUrl: "https://example.com/future-leaders",
    sourceType: "official",
    format: "online",
    location: "India",
    eventStartDate: null,
    eventEndDate: null,
    registrationDeadline: daysFromNow(24),
    eligibility: "Undergraduate students enrolled in an Indian institution.",
    fees: "Free",
    benefit: "Education grant and leadership mentorship.",
    skills: ["Leadership", "Community", "Research"],
    tags: ["funding", "india", "undergraduate"],
    verificationStatus: "officially_verified",
    aiConfidence: 0.96,
    status: "published",
    lastVerifiedAt: now.toISOString(),
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
];
